name: Manual Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            artifact_name: light-control-Windows.zip
            dist_path: dist/main
          - os: macos-latest
            artifact_name: light-control-MacOS.zip
            dist_path: dist/main
          - os: ubuntu-latest
            artifact_name: light-control-Linux.zip
            dist_path: dist/main

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Build Binary
        run: uv run pyinstaller --noconsole --onedir src/light_control/main.py

      - name: Zip Artifact
        shell: bash
        run: |
          # Compress the output folder so users only download one file
          cd dist
          7z a ../${{ matrix.artifact_name }} main/

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}