name: Ruff

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13" ] # Updated for 2025
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5 # Updated to v5 for better caching
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          # Arguments passed to the 'ruff' command
          args: "check --output-format=github"
          # By default, Ruff scans the whole repo recursively
          src: "."